import fs from 'fs'
import path from 'path'

// Read the built Astro HTML
const builtPath = path.join(process.cwd(), 'dist-astro', 'index.html')
const html = fs.readFileSync(builtPath, 'utf-8')

// Escape HTML for TypeScript string literal
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$/g, '\\$')

// Read icons.json to extract icon names
const iconsPath = path.join(process.cwd(), 'icons.json')
const iconsData = JSON.parse(fs.readFileSync(iconsPath, 'utf-8'))
const iconNames = [...new Set(
  Object.keys(iconsData)
    .map(name => name.replace(/-(dark|light)$/i, ''))
    .map(n => n.toLowerCase())
)].sort()

// Generate landing.ts with embedded HTML and icon names
const output = `// Auto-generated by scripts/embed-landing.ts
// Do not edit manually

export const LANDING_HTML = \`${escaped}\`

export const ICON_NAMES = ${JSON.stringify(iconNames, null, 2)}
`

fs.writeFileSync(path.join(process.cwd(), 'src', 'landing.ts'), output)
console.log('embedded astro landing page into src/landing.ts')
