import fs from "fs"
import path from "path"

// Read the built Astro HTML
const builtPath = path.join(process.cwd(), "dist-astro", "index.html")
const html = fs.readFileSync(builtPath, "utf-8")

// Escape HTML for TypeScript string literal
const escaped = html
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$/g, "\\$")

// Generate landing.ts with embedded HTML
const output = `// Auto-generated by scripts/embed-landing.ts
// Do not edit manually

export const LANDING_HTML = \`${escaped}\`
`

fs.writeFileSync(path.join(process.cwd(), "src", "landing.ts"), output)
console.log("embedded astro landing page into src/landing.ts")
